version: "3.3"

volumes:
  produtosdata:

networks:
  frontend:
  backend:

services:
  mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - produtosdata:/var/lib/mysql
    networks:
      - backend
    environment:
      bind-address: "0.0.0.0"
      MYSQL_DATABASE: "FTStore"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "1701"
  ftstore:
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
      - backend
      - frontend
    ports:
      - 5000:80
    environment:
      FTSTORE_DBHOST: mysql
    depends_on:
      - mysql
