FROM mcr.microsoft.com/dotnet/core/sdk:3.1

LABEL version="1.0.2" description="FTStoreDev"
RUN apt-get update -y
RUN curl -sL https://deb.nodesource.com/setup_13.x | bash --debug
RUN apt-get install nodejs -yq
RUN mkdir /app
WORKDIR /app
COPY . .
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+:80
RUN dotnet restore
RUN dotnet publish -c Release -o dist
EXPOSE 80/tcp
ENTRYPOINT ["dotnet","dist/FTStore.Web.dll"]
