version: "3.3"

volumes:
  produtosdata:
  pg_pg:
  pg_pgdata:

networks:
  frontend:
  backend:

services:
  mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - produtosdata:/var/lib/mysql
    networks:
      - backend
    environment:
      # bind-address: "0.0.0.0"
      MYSQL_DATABASE: "FTStore"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "1701"
    ports:
      - 3306:3306
  ftstore:
    build:
      context: .
      dockerfile: ./.Docker/Dockerfile
    networks:
      - backend
      - frontend
    ports:
      - 5000:80
    environment:
      FTSTORE_DBHOST: mysql
      ENV ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - mysql
  db:
    image: postgres:12.0
    container_name: sonarqube-pg
    hostname: sonarqube-pg
    networks:
      - backend
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_pg:/var/lib/postgresql
      - pg_pgdata:/var/lib/postgresql/data
