version: 2.1

executors:
  ftstore-executor:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/ftstore

jobs:
  restore-dependencies:
    executor: ftstore-executor
    steps:
      - checkout
      - run: dotnet restore
      - persist_to_workspace:
          root: ~/
          paths:
            - null
  build:
    executor: ftstore-executor
    steps:
      - run:
          name: "Building"
          command: "dotnet build"
  app-test:
    executor: ftstore-executor
    steps:
      - run:
          name: "Testing"
          command: "dotnet test"
